language: ruby
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
install: "bundle install --jobs 8"
rvm:
  - 2.4.6
  - 2.5.5
  - ruby-head
gemfile:
  - gemfiles/rails42.gemfile
  - gemfiles/rails50.gemfile
  - gemfiles/rails51.gemfile
  - gemfiles/rails52.gemfile
matrix:
  exclude:
    - rvm: ruby-head
      gemfile: gemfiles/rails42.gemfile
  fast_finish: true
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rspec
